//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTMU.OrientationSimulation.WinFormsMain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPTMU.OrientationSimulation.WinFormsMain.Resources.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coning Frequency (rad/s).
        /// </summary>
        internal static string ClassicalConingAngularFrequency {
            get {
                return ResourceManager.GetString("ClassicalConingAngularFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coning Angle (deg).
        /// </summary>
        internal static string ConingAngle {
            get {
                return ResourceManager.GetString("ConingAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application to change language..
        /// </summary>
        internal static string RestartNeeded {
            get {
                return ResourceManager.GetString("RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string SimulationOptionsAlgorithmType {
            get {
                return ResourceManager.GetString("SimulationOptionsAlgorithmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Motion (s).
        /// </summary>
        internal static string SimulationOptionsMotionPeriod {
            get {
                return ResourceManager.GetString("SimulationOptionsMotionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion step (s).
        /// </summary>
        internal static string SimulationOptionsMotionStep {
            get {
                return ResourceManager.GetString("SimulationOptionsMotionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Motion.
        /// </summary>
        internal static string SimulationOptionsMotionType {
            get {
                return ResourceManager.GetString("SimulationOptionsMotionType", resourceCulture);
            }
        }
    }
}
